/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef YiService_CONSTANTS_H
#define YiService_CONSTANTS_H

#include "YiService_types.h"

namespace yisrv {

class YiServiceConstants {
 public:
  YiServiceConstants();

};

extern const YiServiceConstants g_YiService_constants;

} // namespace

#endif
