/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "YiService_constants.h"

namespace yisrv {

const YiServiceConstants g_YiService_constants;

YiServiceConstants::YiServiceConstants() {
}

} // namespace

